### ISSUE TITLE
VSCodium include binaries in package

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [Thilas/chocolatey-packages#17]
It would be nice if the VSCodium package included the installers rather then downloading them. The license is MIT so redistribution is allowed, and the package size would be under the chocolatey.org 200mb limit.

**Comment by Thilas** [comment]
When upgrading it, current package is actually checking first whether VSCodium has already self-upgraded or not. So having the installer included within the package means that users may download the whole thing for nothing.

Instead, I suggest to build a new `vscodium.portable` package that would include the content of the available zip file.

**Comment by Thilas** [comment]
I've been working on creating a portable package and I choose to align on `vscode.portable` behavior (i.e. not embedding the actual program in the chocolatey package). The main reason is that including both zip files (x86 and x64) is really inefficient because it makes users downloading twice as much as they actually need.

So unless there is another way to include binaries, I won't do it.
