### ISSUE TITLE
Update sabnzbd 

### ISSUE THREAD

**Issue by Yankees4life** [Thilas/chocolatey-packages#53]
Hello

There's a new version of sabnzbd available. I hope you can update the package. Cheers

**Comment by Thilas** [comment]
Hi, actually both new versions (4.0.0 & 4.0.1) have been pushed already (e.g. https://community.chocolatey.org/packages/SABnzbd/4.0.1#versionhistory).

Problem is that they won't pass the deployment test because the installer does not support old Windows anymore (tests are done on Windows 2012). According to SABnzbd doc: "The installer only works on Windows 8 and newer" (https://sabnzbd.org/wiki/installation/install-windows).

I requested a permanent exemption as a workaround. We need to wait for an answer now.

**Comment by Thilas** [comment]
New versions have finally been approved
