### ISSUE TITLE
Suppress packageVersion from install path

### ISSUE THREAD

**Issue by r1m** [Thilas/chocolatey-packages#8]
Is it possible to suppress the packageVersion from the install path ?
the /installationPath parameter is still appending package version.

I want my eclipse install to be on $Program/Eclipse/eclipse.exe or whatever static location than doesn't depend on the installed version. This way I can script plugin installation with nodeclipse.

Alternatively, is there a way to find out the final eclipse install path ?

Thanks

**Comment by r1m** [comment]
This is what I use for now
```
$eclipseInstallPath = Join-Path (Join-Path $env:ProgramFiles ( ls $env:ProgramFiles *Eclipse* -Directory)) 'eclipse'
```

**Comment by Thilas** [comment]
Hello, sorry for the delay.

Actually I intended to always have the version in the path in order to make it possible to determine the version from the path.

In order to determine the path to eclipse.exe, I would recommend something like this:
`ls (Join-Path $Env:ProgramFiles 'Eclipse') -Recurse -Include 'eclipse.exe'`

**Comment by r1m** [comment]
Ok, thanks for your help

**Comment by arend-von-reinersdorff** [comment]
I would also prefer a stable installation path. Now I have to recreate my shortcuts for each new Eclipse version.

**Comment by Thilas** [comment]
@arend-von-reinersdorff, my understanding is that is was originally implemented this way so that the package doesn't have to manage eclipse upgrade. And since I don't know much about eclipse either, I left the behavior as is.
